kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: 192.168.0.50:5000/mathematics_arm
    registry: https://192.168.0.50:5000
    insecure: true # get signed cert and remove this | this is only used on local network at the moment

platform:
  os: linux
  arch: arm64

trigger:
  branch:
  - main